# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev2-test',
                'doc_host': 'https://mark-clements.github.io',
                'git_url': 'https://github.com/mark-clements/nbdev2-test',
                'lib_path': 'nbdev2_test'},
  'syms': { 'nbdev2_test.core': { 'nbdev2_test.core.foo': ('core.html#foo', 'nbdev2_test/core.py'),
                                  'nbdev2_test.core.say_hello': ('core.html#say_hello', 'nbdev2_test/core.py')}}}